trigger:
- master

pool:
      vmImage: 'ubuntu-latest'

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build    
    steps:
    - bash: mvn clean package -DskipTests
    - bash: docker build -t=akbarchandani/azure-selenium-docker-linux .
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'akbarchandani-docker-hub'
        repository: 'akbarchandani/azure-selenium-docker-linux'
        command: 'push'
        tags: '$(tag)'
